modLoader = "javafml"
loaderVersion = "[43,)"
license = "GPLv3"

[[mods]]
modId = "dprmreborn"
version = "${version}"
displayName = "Datapack Recipe Maker Reborn"
displayURL="https://changeme.dev/" #optional
logoFile="icon.png" #optional
credits="gloomybanana" #optional
authors="TexTrue, BocchiKessokuTeam" #optional
description = '''

'''

[[dependencies.dprmreborn]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dprmreborn]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.4,)"
ordering = "NONE"
side = "BOTH"
